### ISSUE TITLE
tool_editrolesbycap does not offer a capability search anymore on theme_boost

### ISSUE THREAD

**Issue by abias** [moodleou/moodle-tool_editrolesbycap#6] opened 2017-03-24 10:42 UTC
Hi all,

we are using this plugin in its latest version published on https://moodle.org/plugins/pluginversions.php?plugin=tool_editrolesbycap and I can't see any relevant commits after this version here on Github.

With Moodle 3.2 and theme_boost, I saw that there is no capability search anymore.

Screenshot: Moodle 3.2 and theme_boost:
![bildschirmfoto 2017-03-24 um 11 38 24](https://cloud.githubusercontent.com/assets/1092118/24290822/bb73a010-1086-11e7-9974-837842132526.png)

Screenshot: Moodle 3.2 and theme_clean:
![bildschirmfoto 2017-03-24 um 11 38 31](https://cloud.githubusercontent.com/assets/1092118/24290833/c4ce4afc-1086-11e7-9204-41ad768fdbfa.png)

Thus searching for a capability in the endless dropdown is quite laborious on boost. Browsers don't offer any support as the dropdown is not sorted alphabetically and thus starting to type the capability name does not give any good result.

Would it be possible to bring the capability search back on boost?

Thanks in advance,
Alex

**Comment by timhunt** [comment] 2017-03-24 10:44
I fyou look in the Moodle plugins DB, you will say that this pluigin is marked as not compatible with Moodle 3.2. This is why. Yes, we plan to fix it eventually.

**Comment by timhunt** [comment] 2018-03-16 13:50
Hmm. I can't see what they have changed in Boost to break this. ...

Until I wrote those magic words. Then I realised that since the JavaScript was not being loaded at all, it must be that Moodle no-longer called the toHtml method, and that was indeed the problem. Hence f296722565b9c5ef13edb231ac9873fc31538ebe is the fix.

**Closed by timhunt** 2018-03-16 13:50 UTC

**Comment by abias** [comment] 2018-03-19 07:10
Thanks, Tim, for this fix.
Personally, I liked it better on theme_clean when the list of filtered capabilities had 10 visible lines instead of only 1, but the current solution is far better than having to switch to theme_clean everytime I use this tool.

**Comment by timhunt** [comment] 2018-03-19 07:41
Well, no code changed in this plugin. It seems to be something that theme_boost is doing that has changed the display of multi-line selects. Therefore, a core bug in formslib - I assume. You could file it at tracker.moodle.org (with this plugin in the steps to reproduce) and you could even try to fix it ;-)
